version: "3.8"
services:
    ca_certificate_service:
        image: ghcr.io/andrewjdawes/ca-certificate-service:latest
        restart: always
        expose:
            - 80
        volumes:
            - ca_certificate_service_domain:/app/data/domain
            - ca_certificate_service_ca:/app/data/ca:rw
            - ca_certificate_service_secrets:/app/data/secrets:ro
volumes:
    ca_certificate_service_domain:
    ca_certificate_service_ca:
    ca_certificate_service_secrets:
